{
  "series":{
    "name":"宝马3系 要不要再长一点？",
    "hot":54,
    "good":82,
    "bad":7,
    "neutual":11,
    "group":0
  },
  "nodes":[
    {"name":"性价比高","group":1,"weight":5},
    {"name":"空间大","group":1,"weight":4},
    {"name":"有噪音","group":2,"weight":15},
    {"name":"有气味","group":2,"weight":85},
    {"name":"加速快","group":1,"weight":25},
    {"name":"很长很长的评论哈哈哈","group":3,"weight":5},
    {"name":"Test","group":3,"weight":2}
  ],
  "links":[
    {"source":1,"target":0},
    {"source":2,"target":0,"value":8},
    {"source":3,"target":0,"value":10},
    {"source":4,"target":0,"value":1},
    {"source":5,"target":0,"value":1},
    {"source":6,"target":0,"value":1},
    {"source":7,"target":0,"value":1}
  ]
}
